apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: nodejs-rest-http
      namespace: myproject
      labels:
        project: nodejs-rest-http
        version: 2.0.0
        provider: nodeshift
        app: nodejs-rest-http
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 1700c6b90219d2253bc5185d79375d21d798a0e8
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: nodejs-rest-http
        project: nodejs-rest-http
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - nodejs-rest-http
            from:
              kind: ImageStreamTag
              name: 'nodejs-rest-http:latest'
      template:
        metadata:
          labels:
            project: nodejs-rest-http
            version: 2.0.0
            provider: nodeshift
            app: nodejs-rest-http
          annotations:
            nodeshift/git-branch: master
            nodeshift/git-commit: 1700c6b90219d2253bc5185d79375d21d798a0e8
        spec:
          containers:
            - image: nodejs-rest-http
              name: nodejs-rest-http
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /api/greeting
                  port: 8080
                  scheme: HTTP
              livenessProbe:
                httpGet:
                  path: /api/greeting
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
              env: []
  - apiVersion: v1
    kind: Route
    spec:
      to:
        kind: Service
        name: nodejs-rest-http
      port:
        targetPort: 8080
    metadata:
      name: nodejs-rest-http
      namespace: myproject
      labels:
        project: nodejs-rest-http
        version: 2.0.0
        provider: nodeshift
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: nodejs-rest-http
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: nodejs-rest-http
      namespace: myproject
      labels:
        project: nodejs-rest-http
        version: 2.0.0
        provider: nodeshift
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 1700c6b90219d2253bc5185d79375d21d798a0e8
